development:
  adapter: postgresql
  database: db/new_curriculum_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: db/new_curriculum_test
  pool: 5
  timeout: 5000
  host: localhost


production:
  adapter: postgresql
  database: db/new_curriculum_production
  pool: 5
  timeout: 5000
  host: localhost